version: "2.4"
services:
  mielesolar:
    image: ingmarstein/mielesolar:latest
    command: ["-auto", "500", "-vg", "de-CH"]
    environment:
      INVERTER_ADDRESS: ""
      INVERTER_PORT: 502
      MIELE_USERNAME: ""
      MIELE_PASSWORD: ""
      MIELE_CLIENT_ID: ""
      MIELE_CLIENT_SECRET: ""
      TZ: "Europe/Berlin"
    restart: unless-stopped
