version: "2.4"
services:
  mielesolar:
    image: ingmarstein/mielesolar:latest
    volumes:
      - type: bind
        source: devices.json
        target: /devices.json
    environment:
      ""
    restart: unless-stopped
