#!/bin/bash
case "$1" in
start)
  synosystemctl start pkguser-mielesolar
  ;;
stop)
  synosystemctl stop pkguser-mielesolar
  ;;
status)
  ;;
log)
  exec tail -n 100 -f "/var/packages/mielesolar/target/mielesolar.log"
  ;;
*)
  echo "Usage: $0 {start|stop|status}" >&2
  exit 1
  ;;
esac
exit 0
