name: Build Synology Package (SPK)
on: [push, pull_request]
jobs:
  build:
    name: Build and package
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          GOPROXY: "https://proxy.golang.org"
        run: go build -v

      - name: Package
        env:
          SPK_ARCH: x86_64
          SPK_PACKAGE_VERSION: ${{ github.sha }}
        run: ./.ci/build-package.sh

      - name: Archive package
        uses: actions/upload-artifact@v3
        with:
          name: Synology package
          path: synology/*.spk
